# Generated by Django 2.2 on 2020-05-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Name', models.CharField(max_length=120)),
                ('Unique_ID', models.CharField(max_length=70)),
                ('Email_ID', models.CharField(max_length=120)),
                ('Password', models.CharField(max_length=40)),
                ('Joining_Date', models.DateField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Worksubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueID', models.CharField(max_length=70)),
                ('work_from', models.TimeField()),
                ('Team_Leader', models.CharField(max_length=70)),
                ('Mentor', models.CharField(max_length=70)),
                ('Member_Name', models.CharField(max_length=70)),
                ('Work_Description', models.TextField(max_length=2000)),
                ('work_to', models.TimeField()),
            ],
        ),
    ]
