# Generated by Django 2.2 on 2020-05-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksubmit',
            name='Work_Description',
            field=models.TextField(),
        ),
    ]
