# Generated by Django 2.2 on 2020-05-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0003_auto_20200526_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Email_ID',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Employee_Name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Joining_Date',
            field=models.DateField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Password',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Unique_ID',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
