# Generated by Django 2.2 on 2020-06-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0004_auto_20200527_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksubmit',
            name='work_date',
            field=models.DateField(null=True),
        ),
    ]
