# Generated by Django 2.2 on 2020-05-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0002_auto_20200526_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksubmit',
            name='Member_Name',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='worksubmit',
            name='Mentor',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='worksubmit',
            name='Team_Leader',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='worksubmit',
            name='Work_Description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='worksubmit',
            name='uniqueID',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='worksubmit',
            name='work_from',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='worksubmit',
            name='work_to',
            field=models.TimeField(null=True),
        ),
    ]
